name: "Update README Badge"
description: "Update coverage badge in README.md based on coverage data"

inputs:
  coverage-file:
    description: "Path to coverage file (coverage.xml)"
    required: false
    default: "coverage.xml"
  coverage-format:
    description: "Format of coverage file (xml)"
    required: false
    default: "xml"
  min-coverage-threshold:
    description: "Minimum coverage threshold for color coding"
    required: false
    default: "99.1"
  badge-pattern:
    description: "Pattern to match existing badge in README"
    required: false
    default: 'coverage-[0-9]+\.[0-9]+%25-[a-z]+'

runs:
  using: "composite"
  steps:
    - name: Extract coverage percentage
      id: coverage
      shell: bash
      run: |
        if [ "${{ inputs.coverage-format }}" = "xml" ]; then
          # Extract from XML coverage file
          python -c "
        import xml.etree.ElementTree as ET
        import os
        import sys

        try:
            if not os.path.exists('${{ inputs.coverage-file }}'):
                sys.exit(1)
                
            tree = ET.parse('${{ inputs.coverage-file }}')
            root = tree.getroot()
            
            # Try different attribute names for coverage
            coverage = None
            if 'line-rate' in root.attrib:
                coverage = float(root.attrib['line-rate']) * 100
            elif 'lines-valid' in root.attrib and 'lines-covered' in root.attrib:
                lines_valid = int(root.attrib['lines-valid'])
                lines_covered = int(root.attrib['lines-covered'])
                coverage = (lines_covered / lines_valid) * 100 if lines_valid > 0 else 0
            else:
                # Search for any element with line-rate
                for elem in root.iter():
                    if 'line-rate' in elem.attrib:
                        coverage = float(elem.attrib['line-rate']) * 100
                        break
                else:
                    sys.exit(1)
                
            if coverage is None:
                sys.exit(1)
                
            print(f'coverage={coverage:.1f}')
        except Exception as e:
            sys.exit(1)
        "
        else
          # Extract from text coverage file
          TOTAL_COVERAGE=$(grep -E '^TOTAL' ${{ inputs.coverage-file }} | awk '{print $4}' | tr -d '%' || echo "0")
          echo "coverage=${TOTAL_COVERAGE}"
        fi

    - name: Determine badge color
      id: color
      shell: bash
      run: |
        COVERAGE=${{ steps.coverage.outputs.coverage }}

        if (( $(echo "$COVERAGE < 90" | bc -l) )); then
          echo "color=red"
        elif (( $(echo "$COVERAGE < 99" | bc -l) )); then
          echo "color=orange"
        else
          echo "color=green"
        fi

    - name: Update README badge
      shell: bash
      run: |
        COVERAGE=${{ steps.coverage.outputs.coverage }}
        COLOR=${{ steps.color.outputs.color }}

        NEW_BADGE="coverage-${COVERAGE}%25-${COLOR}"
        CURRENT_BADGE=$(grep -oE '${{ inputs.badge-pattern }}' README.md || echo "")

        if [[ "$CURRENT_BADGE" != "$NEW_BADGE" ]]; then
          sed -i "s|${{ inputs.badge-pattern }}|$NEW_BADGE|g" README.md
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update README with ${COVERAGE}% test coverage"
          git push
        fi
