name: 'Run Tests and Check Coverage'
description: 'Run tests with coverage and check against minimum threshold'

inputs:
  coverage-command:
    description: 'Command to run tests with coverage'
    required: false
    default: 'pytest tests/ --cov=arklex --cov-report=term-missing --cov-report=html --cov-report=xml --no-cov-on-fail'
  min-coverage-threshold:
    description: 'Minimum coverage percentage to pass'
    required: false
    default: '99.1'
  checkout-repo:
    description: 'Whether to checkout the repository (set to false if already checked out)'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      if: inputs.checkout-repo == 'true'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      if: inputs.checkout-repo == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      if: inputs.checkout-repo == 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[milvus,shopify,hubspot]' --quiet

    - name: Run tests and check coverage threshold
      id: coverage-check
      shell: bash
      env:
        MIN_COVERAGE_THRESHOLD: ${{ inputs.min-coverage-threshold }}
        ARKLEX_TEST_ENV: 'local'
      run: |
        ${{ inputs.coverage-command }}

        # Check if coverage.xml exists, if not try to generate it
        if [ ! -f "coverage.xml" ] && [ -f ".coverage" ]; then
          coverage xml
        fi

        python -c "
        import xml.etree.ElementTree as ET
        import os
        import sys

        try:
            if not os.path.exists('coverage.xml'):
                sys.exit(1)
                
            tree = ET.parse('coverage.xml')
            root = tree.getroot()
            
            # Try different attribute names for coverage
            coverage = None
            if 'line-rate' in root.attrib:
                coverage = float(root.attrib['line-rate']) * 100
            elif 'lines-valid' in root.attrib and 'lines-covered' in root.attrib:
                lines_valid = int(root.attrib['lines-valid'])
                lines_covered = int(root.attrib['lines-covered'])
                coverage = (lines_covered / lines_valid) * 100 if lines_valid > 0 else 0
            else:
                # Search for any element with line-rate
                for elem in root.iter():
                    if 'line-rate' in elem.attrib:
                        coverage = float(elem.attrib['line-rate']) * 100
                        break
                else:
                    sys.exit(1)
                
            if coverage is None:
                sys.exit(1)

            min_coverage = float(os.environ.get('MIN_COVERAGE_THRESHOLD', '${{ inputs.min-coverage-threshold }}'))

            if coverage < min_coverage:
                sys.exit(1)

            with open(os.environ.get('GITHUB_OUTPUT', '/dev/null'), 'a') as f:
                f.write(f'coverage={coverage:.1f}\\n')
        except Exception as e:
            sys.exit(1)"
