name: Reusable Display Coverage Comment

on:
  workflow_call:
    inputs:
      minimum-green:
        description: 'Minimum coverage percentage for green status'
        required: false
        default: '99.1'
        type: string
      minimum-orange:
        description: 'Minimum coverage percentage for orange status'
        required: false
        default: '70'
        type: string
    secrets:
      github-token:
        description: 'GitHub token for authentication'
        required: true

jobs:
  display-coverage:
    name: Display Coverage Comment
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    steps:
      - name: Display coverage comment
        id: coverage
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          MINIMUM_GREEN: ${{ inputs.minimum-green }}
          MINIMUM_ORANGE: ${{ inputs.minimum-orange }}
