name: Test Coverage Check

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    name: run tests and display coverage

    if: github.base_ref == 'main' && github.event.label.name == 'run-coverage-tests'

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    env:
      SHOPIFY_FIXED_ARGS: ${{ secrets.SHOPIFY_FIXED_ARGS }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MIN_COVERAGE_THRESHOLD: '99.1'

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[milvus,shopify,hubspot]' --quiet

      - name: Run tests and check coverage threshold
        id: coverage-check
        uses: ./.github/actions/run-coverage-tests.yml
        with:
          coverage-command: 'pytest tests/ --cov=arklex --cov-report=term-missing --cov-report=html --cov-report=xml --no-cov-on-fail'
          min-coverage-threshold: '99.1'

      - name: Upload coverage report
        uses: ./.github/actions/upload-coverage-report.yml

      - name: Display coverage comment
        id: coverage
        uses: ./.github/actions/display-coverage-comment.yml
        with:
          github-token: ${{ github.token }}
          minimum-green: '99.1'
          minimum-orange: '70'

      - name: Update README badge
        if: github.ref == 'refs/heads/main'
        uses: ./.github/actions/update-badge.yml
        with:
          coverage-file: 'coverage.xml'
          coverage-format: 'xml'
          min-coverage-threshold: '99.1'
