name: Test Coverage Check

on:
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  setup:
    name: Setup Environment
    if: github.base_ref == 'main' && github.event.label.name == 'run-coverage-tests'
    runs-on: ubuntu-latest
    outputs:
      coverage-percentage: ${{ steps.coverage-check.outputs.coverage }}
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ github.token }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[milvus,shopify,hubspot]' --quiet

      - name: Run tests and check coverage threshold
        id: coverage-check
        uses: ./.github/actions/run-coverage-tests
        with:
          coverage-command: 'pytest tests/ --cov=arklex --cov-report=term-missing --cov-report=html --cov-report=xml --no-cov-on-fail'
          min-coverage-threshold: '99.1'

  upload-coverage:
    name: Upload Coverage Report
    needs: setup
    if: github.base_ref == 'main' && github.event.label.name == 'run-coverage-tests'
    uses: ./.github/workflows/reusable-upload-coverage-report.yml

  display-coverage:
    name: Display Coverage Comment
    needs: setup
    if: github.base_ref == 'main' && github.event.label.name == 'run-coverage-tests'
    uses: ./.github/workflows/reusable-display-coverage-comment.yml
    with:
      github-token: ${{ github.token }}
      minimum-green: '99.1'
      minimum-orange: '70'

  update-badge:
    name: Update README Badge
    needs: setup
    if: github.base_ref == 'main' && github.event.label.name == 'run-coverage-tests' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable-update-badge.yml
    with:
      coverage-file: 'coverage.xml'
      coverage-format: 'xml'
      min-coverage-threshold: '99.1'
