name: Coverage Regression Check

on:
  pull_request:
    types: [labeled]

jobs:
  check-regression:
    name: Detect Coverage Regression by File
    if: github.base_ref == 'main' && github.event.label.name == 'run-coverage-regression-test'
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SHOPIFY_FIXED_ARGS: ${{ secrets.SHOPIFY_FIXED_ARGS }}

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[milvus,shopify,hubspot]' --quiet
          pip install diff-cover coverage

      - name: Run tests and collect coverage
        id: coverage
        run: |
          # Run tests with coverage
          coverage run -m pytest tests/
          
          # Generate coverage reports
          coverage xml
          coverage html
          coverage report
          
          # Extract coverage percentage
          if [ -f "coverage.xml" ]; then
            COVERAGE=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); print(f'{float(tree.getroot().attrib[\"line-rate\"]) * 100:.1f}')")
            echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
            echo "✅ Coverage: ${COVERAGE}%"
          else
            echo "❌ No coverage data collected"
            exit 1
          fi

      - name: Check for Python file changes
        id: changes
        run: |
          if git diff --name-only origin/main | grep -q '\.py$'; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "✅ Python files changed - will check coverage regression"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No Python files changed - skipping regression check"
          fi

      - name: Check coverage regression
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          echo "🔍 Checking coverage regression..."
          diff-cover coverage.xml --compare-branch origin/main --fail-under=100

      - name: Generate diff coverage report
        if: steps.changes.outputs.has_changes == 'true' && failure()
        run: |
          diff-cover coverage.xml --compare-branch origin/main --html-report diff_coverage.html || true

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            htmlcov/
        continue-on-error: true

      - name: Upload diff coverage report
        if: steps.changes.outputs.has_changes == 'true' && failure()
        uses: actions/upload-artifact@v4
        with:
          name: diff-coverage-report
          path: diff_coverage.html
        continue-on-error: true

      - name: Display coverage in PR
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 99.1
          MINIMUM_ORANGE: 70
        continue-on-error: true

      - name: Update README badge
        run: |
          if [ -f "coverage.xml" ]; then
            COVERAGE=${{ steps.coverage.outputs.coverage }}
            
            # Determine badge color
            if (( $(echo "$COVERAGE < 90" | bc -l) )); then
              COLOR="red"
            elif (( $(echo "$COVERAGE < 99" | bc -l) )); then
              COLOR="orange"
            else
              COLOR="green"
            fi
            
            # Update README badge
            sed -i "s/coverage-[0-9]\+\.[0-9]%25-[a-z]*/coverage-${COVERAGE}%25-${COLOR}/g" README.md
            
            # Commit if changed
            if ! git diff --quiet; then
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git add README.md
              git commit -m "chore: update README with ${COVERAGE}% test coverage"
              git push
            fi
          fi
